# PostgreSQL Configuration Generator
# Fireball Industries - Industrial IoT Edition
# Author: Patrick Ryan
#
# Usage:
#   .\generate-config.ps1 -Scenario <scenario> [-OutputFile <file>]
#
# Scenarios:
#   dev-minimal, factory-monitoring, ha-production, edge-gateway, data-warehouse, compliance

[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)]
    [ValidateSet('dev-minimal', 'factory-monitoring', 'ha-production', 'edge-gateway', 'data-warehouse', 'compliance')]
    [string]$Scenario,
    
    [Parameter(Mandatory=$false)]
    [string]$OutputFile = "",
    
    [Parameter(Mandatory=$false)]
    [string]$ReleaseName = "postgresql",
    
    [Parameter(Mandatory=$false)]
    [string]$Namespace = "databases"
)

function Write-Info {
    param([string]$Message)
    Write-Host "ℹ $Message" -ForegroundColor Cyan
}

function Write-Success {
    param([string]$Message)
    Write-Host "✓ $Message" -ForegroundColor Green
}

Write-Host ""
Write-Host "═══════════════════════════════════════════════════════════════════" -ForegroundColor Magenta
Write-Host "  PostgreSQL Configuration Generator - Fireball Industries" -ForegroundColor Magenta
Write-Host "═══════════════════════════════════════════════════════════════════" -ForegroundColor Magenta
Write-Host ""

# Configuration templates
$configs = @{
    'dev-minimal' = @"
# Development/Testing Configuration
# Minimal resources for local development
# Generated by Patrick Ryan's config generator

deploymentMode: standalone
resourcePreset: small

postgresql:
  auth:
    database: dev_database
    username: developer
  
  extensions:
    timescaledb:
      enabled: false
    postgis:
      enabled: false
  
  initialDatabases:
    - name: dev_database
      owner: developer
      encoding: UTF8
      locale: en_US.utf8

persistence:
  enabled: true
  size: 10Gi

backup:
  enabled: false

monitoring:
  enabled: false

development:
  enabled: true
  sampleData: true

security:
  tls:
    enabled: false
  
  podSecurityContext:
    runAsNonRoot: false  # Relaxed for dev
"@

    'factory-monitoring' = @"
# Factory Monitoring Configuration
# Production deployment with TimescaleDB for SCADA data
# Optimized for time-series industrial IoT workloads

deploymentMode: standalone
resourcePreset: medium

postgresql:
  auth:
    database: scada_historian
    username: scada_user
  
  extensions:
    timescaledb:
      enabled: true
    postgis:
      enabled: true  # For factory floor layouts
    pgStatStatements:
      enabled: true
  
  initialDatabases:
    - name: scada_historian
      owner: scada_user
      encoding: UTF8
      locale: en_US.utf8
    
    - name: production_data
      owner: scada_user
      encoding: UTF8
      locale: en_US.utf8
    
    - name: quality_metrics
      owner: scada_user
      encoding: UTF8
      locale: en_US.utf8
    
    - name: energy_consumption
      owner: scada_user
      encoding: UTF8
      locale: en_US.utf8
  
  config:
    # Optimized for time-series writes
    checkpoint_timeout: "10min"
    max_wal_size: "2GB"
    shared_buffers: "2GB"
    work_mem: "32MB"

persistence:
  enabled: true
  size: 200Gi
  
  wal:
    enabled: true
    size: 50Gi

backup:
  enabled: true
  schedule: "0 2 * * *"  # 2 AM daily
  retention: 30
  destination:
    type: pvc
    pvc:
      size: 100Gi

monitoring:
  enabled: true
  exporter:
    enabled: true
  serviceMonitor:
    interval: 30s

pgbouncer:
  enabled: true
  poolMode: transaction
  maxClientConn: 500
  defaultPoolSize: 25
"@

    'ha-production' = @"
# High Availability Production Configuration
# 3-node streaming replication with synchronous commit
# For mission-critical production workloads

deploymentMode: ha
resourcePreset: large

highAvailability:
  enabled: true
  replicas: 3
  
  replication:
    synchronous: true
    synchronousCommit: "remote_apply"
    numSynchronousReplicas: 1

postgresql:
  auth:
    database: production_data
    username: app_user
    authMethod: "scram-sha-256"
  
  extensions:
    timescaledb:
      enabled: true
    postgis:
      enabled: true
    pgStatStatements:
      enabled: true
  
  initialDatabases:
    - name: production_data
      owner: app_user
      encoding: UTF8
      locale: en_US.utf8
    
    - name: quality_metrics
      owner: app_user
      encoding: UTF8
      locale: en_US.utf8
    
    - name: maintenance_logs
      owner: app_user
      encoding: UTF8
      locale: en_US.utf8
    
    - name: energy_consumption
      owner: app_user
      encoding: UTF8
      locale: en_US.utf8
    
    - name: scada_historian
      owner: app_user
      encoding: UTF8
      locale: en_US.utf8
    
    - name: audit_trail
      owner: app_user
      encoding: UTF8
      locale: en_US.utf8
  
  config:
    max_connections: "1000"
    shared_buffers: "8GB"
    effective_cache_size: "24GB"
    work_mem: "32MB"
    maintenance_work_mem: "2GB"
    checkpoint_timeout: "15min"
    max_wal_size: "4GB"

persistence:
  enabled: true
  size: 500Gi
  storageClass: "fast-ssd"  # Use your fast storage class
  
  wal:
    enabled: true
    size: 100Gi
    storageClass: "fast-ssd"

backup:
  enabled: true
  schedule: "0 */6 * * *"  # Every 6 hours
  retention: 60  # 60 days
  destination:
    type: pvc
    pvc:
      size: 1Ti
      storageClass: "standard"

monitoring:
  enabled: true
  exporter:
    enabled: true
  serviceMonitor:
    interval: 15s

pgbouncer:
  enabled: true
  poolMode: transaction
  maxClientConn: 2000
  defaultPoolSize: 50

security:
  tls:
    enabled: true
    source: cert-manager
    certManager:
      issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
  
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 999
    fsGroup: 999
    seccompProfile:
      type: RuntimeDefault

networkPolicy:
  enabled: true

podDisruptionBudget:
  enabled: true
  minAvailable: 2  # Always keep 2 replicas running

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: postgresql-pod
        topologyKey: kubernetes.io/hostname
"@

    'edge-gateway' = @"
# Edge Gateway Configuration
# Lightweight deployment for edge computing/IoT gateways
# Optimized for resource-constrained environments

deploymentMode: standalone
resourcePreset: edge

postgresql:
  auth:
    database: edge_data
    username: edge_user
  
  extensions:
    timescaledb:
      enabled: true
    postgis:
      enabled: false  # Disabled to save resources
    pgStatStatements:
      enabled: false
  
  initialDatabases:
    - name: edge_data
      owner: edge_user
      encoding: UTF8
      locale: en_US.utf8
    
    - name: sensor_buffer
      owner: edge_user
      encoding: UTF8
      locale: en_US.utf8
  
  config:
    max_connections: "100"
    shared_buffers: "128MB"
    work_mem: "4MB"
    # Aggressive autovacuum for small datasets
    autovacuum_naptime: "30s"

persistence:
  enabled: true
  size: 10Gi

backup:
  enabled: true
  schedule: "0 3 * * *"
  retention: 7  # Only keep 1 week on edge
  destination:
    type: pvc
    pvc:
      size: 20Gi

monitoring:
  enabled: true
  exporter:
    enabled: true

pgbouncer:
  enabled: false  # Save resources

security:
  tls:
    enabled: false

# Tolerate edge node taints
tolerations:
  - key: "node-role.kubernetes.io/edge"
    operator: "Exists"
    effect: "NoSchedule"

nodeSelector:
  node-role.kubernetes.io/edge: ""
"@

    'data-warehouse' = @"
# Data Warehouse Configuration
# Optimized for analytics and reporting workloads
# Large memory allocation, parallel query execution

deploymentMode: standalone
resourcePreset: xlarge

postgresql:
  auth:
    database: analytics
    username: analyst
  
  extensions:
    timescaledb:
      enabled: true
    postgis:
      enabled: true
    pgStatStatements:
      enabled: true
  
  initialDatabases:
    - name: analytics
      owner: analyst
      encoding: UTF8
      locale: en_US.utf8
    
    - name: historical_data
      owner: analyst
      encoding: UTF8
      locale: en_US.utf8
  
  config:
    # Analytics-optimized settings
    max_connections: "200"
    shared_buffers: "16GB"
    effective_cache_size: "48GB"
    work_mem: "128MB"  # Large work_mem for complex queries
    maintenance_work_mem: "4GB"
    
    # Parallel query settings
    max_parallel_workers_per_gather: "4"
    max_parallel_workers: "8"
    max_worker_processes: "8"
    
    # Optimizer settings
    random_page_cost: "1.1"
    effective_io_concurrency: "200"
    
    # Less frequent checkpoints (analytics is read-heavy)
    checkpoint_timeout: "30min"
    max_wal_size: "8GB"

persistence:
  enabled: true
  size: 1Ti
  storageClass: "fast-ssd"

backup:
  enabled: true
  schedule: "0 1 * * 0"  # Weekly on Sunday
  retention: 90
  destination:
    type: pvc
    pvc:
      size: 500Gi

monitoring:
  enabled: true
  exporter:
    enabled: true
  serviceMonitor:
    interval: 60s

pgbouncer:
  enabled: false  # Analytics queries are long-running

# Custom PostgreSQL settings for analytics
customPostgresqlConf:
  default_statistics_target: "100"
  constraint_exclusion: "partition"
  from_collapse_limit: "12"
  join_collapse_limit: "12"
"@

    'compliance' = @"
# Compliance Configuration
# 21 CFR Part 11, ISO 9001, GDPR compliant
# Audit logging, encryption, data retention policies

deploymentMode: ha
resourcePreset: large

highAvailability:
  enabled: true
  replicas: 3
  replication:
    synchronous: true
    synchronousCommit: "remote_apply"
    numSynchronousReplicas: 2  # Extra safety

postgresql:
  auth:
    database: production_data
    username: app_user
    authMethod: "scram-sha-256"  # Strong authentication
  
  extensions:
    timescaledb:
      enabled: true
    postgis:
      enabled: true
    pgStatStatements:
      enabled: true
  
  initialDatabases:
    - name: production_data
      owner: app_user
      encoding: UTF8
      locale: en_US.utf8
    
    - name: audit_trail
      owner: app_user
      encoding: UTF8
      locale: en_US.utf8
    
    - name: quality_records
      owner: app_user
      encoding: UTF8
      locale: en_US.utf8
  
  config:
    # Extensive logging for compliance
    log_statement: "all"
    log_connections: "on"
    log_disconnections: "on"
    log_duration: "on"
    log_hostname: "on"
    log_line_prefix: "%t [%p] [%u@%d] [%h] "
    
    # Data integrity
    fsync: "on"
    synchronous_commit: "remote_apply"
    full_page_writes: "on"

persistence:
  enabled: true
  size: 500Gi
  storageClass: "encrypted-ssd"  # Use encrypted storage class

backup:
  enabled: true
  schedule: "0 */4 * * *"  # Every 4 hours
  retention: 2555  # 7 years for FDA compliance
  destination:
    type: s3
    s3:
      bucket: "compliance-backups"
      region: "us-east-1"
      # Use existing secret for S3 credentials

monitoring:
  enabled: true
  exporter:
    enabled: true
  serviceMonitor:
    interval: 15s

security:
  tls:
    enabled: true
    source: cert-manager
    certManager:
      issuerRef:
        name: compliance-issuer
        kind: ClusterIssuer
  
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 999
    fsGroup: 999
    seccompProfile:
      type: RuntimeDefault
  
  encryptionAtRest:
    enabled: true

networkPolicy:
  enabled: true
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              compliance-zone: "validated"

podDisruptionBudget:
  enabled: true
  minAvailable: 2

compliance:
  cfrPart11:
    enabled: true
    auditLogging: true
    electronicSignatures: true
    dataIntegrity: true
  
  iso9001:
    enabled: true
    documentControl: true
    recordRetention: true
  
  gdpr:
    enabled: true
    dataEncryption: true
    rightToBeForgotten: true
    auditTrail: true
"@
}

# Generate configuration
$config = $configs[$Scenario]

if (-not $config) {
    Write-Host "✗ Unknown scenario: $Scenario" -ForegroundColor Red
    exit 1
}

Write-Info "Generating configuration for scenario: $Scenario"

# Determine output file
if (-not $OutputFile) {
    $OutputFile = "$Scenario-values.yaml"
}

# Write configuration
$config | Out-File -FilePath $OutputFile -Encoding UTF8

Write-Success "Configuration generated: $OutputFile"
Write-Host ""
Write-Info "To deploy with this configuration:"
Write-Host "  helm install $ReleaseName . -f $OutputFile -n $Namespace" -ForegroundColor White
Write-Host ""
Write-Info "Or use the management script:"
Write-Host "  .\scripts\manage-postgresql.ps1 -Action deploy -ReleaseName $ReleaseName -Namespace $Namespace -ValuesFile $OutputFile" -ForegroundColor White
Write-Host ""

# Scenario-specific tips
switch ($Scenario) {
    'dev-minimal' {
        Write-Host "💡 Dev Tips:" -ForegroundColor Yellow
        Write-Host "  - This is NOT for production use" -ForegroundColor Gray
        Write-Host "  - Security is relaxed for easier development" -ForegroundColor Gray
        Write-Host "  - Backups are disabled to save resources" -ForegroundColor Gray
    }
    'factory-monitoring' {
        Write-Host "💡 Factory Monitoring Tips:" -ForegroundColor Yellow
        Write-Host "  - TimescaleDB is enabled for time-series SCADA data" -ForegroundColor Gray
        Write-Host "  - PostGIS is enabled for spatial factory floor data" -ForegroundColor Gray
        Write-Host "  - Connection pooling is enabled for high concurrency" -ForegroundColor Gray
    }
    'ha-production' {
        Write-Host "💡 HA Production Tips:" -ForegroundColor Yellow
        Write-Host "  - Ensure you have 3+ worker nodes for anti-affinity" -ForegroundColor Gray
        Write-Host "  - Update storageClass to your cluster's fast storage" -ForegroundColor Gray
        Write-Host "  - Configure cert-manager for TLS" -ForegroundColor Gray
    }
    'edge-gateway' {
        Write-Host "💡 Edge Gateway Tips:" -ForegroundColor Yellow
        Write-Host "  - Optimized for resource-constrained edge devices" -ForegroundColor Gray
        Write-Host "  - Ensure edge nodes are labeled correctly" -ForegroundColor Gray
        Write-Host "  - Consider offline backup strategies" -ForegroundColor Gray
    }
    'data-warehouse' {
        Write-Host "💡 Data Warehouse Tips:" -ForegroundColor Yellow
        Write-Host "  - Optimized for complex analytical queries" -ForegroundColor Gray
        Write-Host "  - Large work_mem allows in-memory operations" -ForegroundColor Gray
        Write-Host "  - Consider materialized views for common queries" -ForegroundColor Gray
    }
    'compliance' {
        Write-Host "💡 Compliance Tips:" -ForegroundColor Yellow
        Write-Host "  - Review and customize audit logging requirements" -ForegroundColor Gray
        Write-Host "  - Configure S3 backup credentials" -ForegroundColor Gray
        Write-Host "  - Ensure encrypted storage class exists" -ForegroundColor Gray
        Write-Host "  - Test restore procedures regularly" -ForegroundColor Gray
    }
}

Write-Host ""
Write-Success "Configuration ready to deploy! ☕"
Write-Host ""
