{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "postgresql-pod.fullname" . }}
  namespace: {{ include "postgresql-pod.namespace" . }}
  labels:
    {{- include "postgresql-pod.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "postgresql-pod.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow PostgreSQL connections
    - ports:
        - protocol: TCP
          port: 5432
      {{- with .Values.networkPolicy.ingress }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
    
    {{- if .Values.monitoring.exporter.enabled }}
    # Allow Prometheus scraping
    - ports:
        - protocol: TCP
          port: {{ .Values.monitoring.exporter.port }}
      from:
        - namespaceSelector:
            matchLabels:
              name: monitoring
    {{- end }}
    
    {{- if eq (include "postgresql-pod.isHA" .) "true" }}
    # Allow replication between pods
    - ports:
        - protocol: TCP
          port: 5432
      from:
        - podSelector:
            matchLabels:
              {{- include "postgresql-pod.selectorLabels" . | nindent 14 }}
    {{- end }}
  
  egress:
    # Allow DNS
    - ports:
        - protocol: UDP
          port: 53
    
    # Allow outbound to backup destinations
    {{- if .Values.backup.enabled }}
    - ports:
        - protocol: TCP
          port: 443  # S3/HTTPS
    {{- end }}
    
    {{- with .Values.networkPolicy.egress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
