{{- if eq (include "postgresql-pod.isHA" .) "true" -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "postgresql-pod.fullname" . }}
  namespace: {{ include "postgresql-pod.namespace" . }}
  labels:
    {{- include "postgresql-pod.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "postgresql-pod.fullname" . }}-headless
  replicas: {{ include "postgresql-pod.replicas" . }}
  selector:
    matchLabels:
      {{- include "postgresql-pod.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "postgresql-pod.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.global.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "postgresql-pod.serviceAccountName" . }}
      {{- with .Values.security.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        # Initialize replication based on pod ordinal
        - name: init-replication
          image: {{ include "postgresql-pod.image" . }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          command:
            - /bin/bash
            - -c
            - |
              set -ex
              # Get pod ordinal from hostname
              [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
              ordinal=${BASH_REMATCH[1]}
              
              # If this is pod-0, it's the primary
              if [[ $ordinal -eq 0 ]]; then
                echo "I am the primary (pod-0). No replication setup needed."
                exit 0
              fi
              
              # For replicas, set up streaming replication
              echo "I am replica pod-$ordinal. Setting up replication from primary."
              
              # Wait for primary to be ready
              until pg_isready -h {{ include "postgresql-pod.fullname" . }}-0.{{ include "postgresql-pod.fullname" . }}-headless.{{ include "postgresql-pod.namespace" . }}.svc.cluster.local -p 5432; do
                echo "Waiting for primary to be ready..."
                sleep 2
              done
              
              # Use pg_basebackup to clone from primary
              PGPASSWORD=$REPLICATION_PASSWORD pg_basebackup -h {{ include "postgresql-pod.fullname" . }}-0.{{ include "postgresql-pod.fullname" . }}-headless.{{ include "postgresql-pod.namespace" . }}.svc.cluster.local \
                -D /var/lib/postgresql/data/pgdata \
                -U {{ .Values.highAvailability.replication.username }} \
                -v -P -R -X stream -c fast
              
              echo "Replication setup complete!"
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: REPLICATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgresql-pod.fullname" . }}
                  key: replication-password
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
        {{- with .Values.initContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      
      containers:
        - name: postgresql
          image: {{ include "postgresql-pod.image" . }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          {{- with .Values.security.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: postgresql
              containerPort: 5432
              protocol: TCP
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.auth.username | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgresql-pod.fullname" . }}
                  key: password
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.auth.database | quote }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_REPLICATION_USER
              value: {{ .Values.highAvailability.replication.username | quote }}
            - name: POSTGRES_REPLICATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgresql-pod.fullname" . }}
                  key: replication-password
            {{- if .Values.postgresql.extensions.timescaledb.enabled }}
            - name: TIMESCALEDB_ENABLED
              value: "true"
            {{- end }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            {{- if .Values.persistence.wal.enabled }}
            - name: wal
              mountPath: {{ .Values.persistence.wal.mountPath }}
            {{- end }}
            - name: config
              mountPath: /etc/postgresql/postgresql.conf
              subPath: postgresql.conf
            - name: config
              mountPath: /etc/postgresql/pg_hba.conf
              subPath: pg_hba.conf
            {{- if .Values.postgresql.initScripts.enabled }}
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
            {{- end }}
            {{- if .Values.security.tls.enabled }}
            - name: certs
              mountPath: /etc/postgresql/certs
              readOnly: true
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U {{ .Values.postgresql.auth.username }} -h 127.0.0.1 -p 5432
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - -e
                - |
                  exec pg_isready -U {{ .Values.postgresql.auth.username }} -h 127.0.0.1 -p 5432
                  [ -f /var/lib/postgresql/data/pgdata/postmaster.pid ] || exit 1
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          resources:
            {{- include "postgresql-pod.resources" . | nindent 12 }}
        
        {{- if .Values.pgbouncer.enabled }}
        - name: pgbouncer
          image: {{ printf "%s/%s:%s" .Values.pgbouncer.image.registry .Values.pgbouncer.image.repository .Values.pgbouncer.image.tag }}
          imagePullPolicy: {{ .Values.pgbouncer.image.pullPolicy }}
          ports:
            - name: pgbouncer
              containerPort: 6432
              protocol: TCP
          env:
            - name: POSTGRESQL_HOST
              value: "127.0.0.1"
            - name: POSTGRESQL_PORT
              value: "5432"
            - name: POSTGRESQL_USERNAME
              value: {{ .Values.postgresql.auth.username | quote }}
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgresql-pod.fullname" . }}
                  key: password
            - name: POSTGRESQL_DATABASE
              value: {{ .Values.postgresql.auth.database | quote }}
            - name: PGBOUNCER_POOL_MODE
              value: {{ .Values.pgbouncer.poolMode | quote }}
            - name: PGBOUNCER_MAX_CLIENT_CONN
              value: {{ .Values.pgbouncer.maxClientConn | quote }}
            - name: PGBOUNCER_DEFAULT_POOL_SIZE
              value: {{ .Values.pgbouncer.defaultPoolSize | quote }}
          resources:
            {{- toYaml .Values.pgbouncer.resources | nindent 12 }}
        {{- end }}
        
        {{- if .Values.monitoring.exporter.enabled }}
        - name: postgres-exporter
          image: {{ printf "%s/%s:%s" .Values.monitoring.exporter.image.registry .Values.monitoring.exporter.image.repository .Values.monitoring.exporter.image.tag }}
          imagePullPolicy: {{ .Values.monitoring.exporter.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: {{ .Values.monitoring.exporter.port }}
              protocol: TCP
          env:
            - name: DATA_SOURCE_URI
              value: "127.0.0.1:5432/{{ .Values.postgresql.auth.database }}?sslmode=disable"
            - name: DATA_SOURCE_USER
              value: {{ .Values.postgresql.auth.username | quote }}
            - name: DATA_SOURCE_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgresql-pod.fullname" . }}
                  key: password
          resources:
            {{- toYaml .Values.monitoring.exporter.resources | nindent 12 }}
        {{- end }}
        
        {{- with .Values.sidecars }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      
      volumes:
        - name: config
          configMap:
            name: {{ include "postgresql-pod.fullname" . }}-config
        {{- if .Values.postgresql.initScripts.enabled }}
        - name: init-scripts
          configMap:
            name: {{ include "postgresql-pod.fullname" . }}-init-scripts
        {{- end }}
        {{- if .Values.security.tls.enabled }}
        - name: certs
          secret:
            secretName: {{ .Values.security.tls.secretName }}
            defaultMode: 0600
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
  
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          {{- include "postgresql-pod.labels" . | nindent 10 }}
        {{- with .Values.persistence.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
          - {{ .Values.persistence.accessMode }}
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ include "postgresql-pod.storageSize" . }}
    
    {{- if .Values.persistence.wal.enabled }}
    - metadata:
        name: wal
        labels:
          {{- include "postgresql-pod.labels" . | nindent 10 }}
      spec:
        accessModes:
          - {{ .Values.persistence.accessMode }}
        {{- if .Values.persistence.wal.storageClass }}
        storageClassName: {{ .Values.persistence.wal.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.wal.size }}
    {{- end }}
{{- end }}
