{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    {{- include "grafana-loki.labels" . | nindent 4 }}
    fireball.industries/managed-by: helm
{{- end }}
