{{- if .Values.pod.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "grafana-loki.serviceAccountName" . }}
  namespace: {{ include "grafana-loki.namespace" . }}
  labels:
    {{- include "grafana-loki.labels" . | nindent 4 }}
  {{- with .Values.pod.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
