{{- if .Values.namespace.create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "emberburn.namespace" . }}
  labels:
    {{- toYaml .Values.namespace.labels | nindent 4 }}
    {{- include "emberburn.labels" . | nindent 4 }}
{{- end }}
