{{- if .Values.pod.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "emberburn.serviceAccountName" . }}
  namespace: {{ include "emberburn.namespace" . }}
  labels:
    {{- include "emberburn.labels" . | nindent 4 }}
  {{- with .Values.pod.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
